/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicapp;

/**
 *
 * @author carlos
 */
public class Ecualizador extends javax.swing.JFrame {

    public Ecualizador(VentanaPrincipal VP){
        this();
        this.VP=VP;
    }
    
    private Ecualizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbEcualizador = new javax.swing.JComboBox<>();
        cbActivoEcualizador = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        slPreamplificador = new javax.swing.JSlider();
        sl32 = new javax.swing.JSlider();
        sl64 = new javax.swing.JSlider();
        sl125 = new javax.swing.JSlider();
        sl250 = new javax.swing.JSlider();
        sl500 = new javax.swing.JSlider();
        sl1K = new javax.swing.JSlider();
        sl2K = new javax.swing.JSlider();
        sl16K = new javax.swing.JSlider();
        sl8K = new javax.swing.JSlider();
        sl4K = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Ecualizador");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cbEcualizador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Uniforme", "Pop", "Rock", "Amplificador de bajos", "Amplificador de agudos" }));
        cbEcualizador.setSelectedItem("Uniforme");
        cbEcualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEcualizadorActionPerformed(evt);
            }
        });

        cbActivoEcualizador.setText("Activo");
        cbActivoEcualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActivoEcualizadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel1.setText("32");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel2.setText("Preamplificador");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel3.setText("64");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel4.setText("125");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel6.setText("250");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel7.setText("500");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel8.setText("1K");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel9.setText("2K");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel10.setText("8K");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel11.setText("4K");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel12.setText("16K");

        slPreamplificador.setMaximum(8);
        slPreamplificador.setMinimum(-8);
        slPreamplificador.setMinorTickSpacing(2);
        slPreamplificador.setOrientation(javax.swing.JSlider.VERTICAL);
        slPreamplificador.setPaintTicks(true);
        slPreamplificador.setValue(0);
        slPreamplificador.setRequestFocusEnabled(false);
        slPreamplificador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slPreamplificadorMouseDragged(evt);
            }
        });

        sl32.setMaximum(8);
        sl32.setMinimum(-8);
        sl32.setMinorTickSpacing(2);
        sl32.setOrientation(javax.swing.JSlider.VERTICAL);
        sl32.setPaintTicks(true);
        sl32.setValue(0);
        sl32.setRequestFocusEnabled(false);
        sl32.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl32MouseDragged(evt);
            }
        });

        sl64.setMaximum(8);
        sl64.setMinimum(-8);
        sl64.setMinorTickSpacing(2);
        sl64.setOrientation(javax.swing.JSlider.VERTICAL);
        sl64.setPaintTicks(true);
        sl64.setValue(0);
        sl64.setRequestFocusEnabled(false);
        sl64.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl64MouseDragged(evt);
            }
        });

        sl125.setMaximum(8);
        sl125.setMinimum(-8);
        sl125.setMinorTickSpacing(2);
        sl125.setOrientation(javax.swing.JSlider.VERTICAL);
        sl125.setPaintTicks(true);
        sl125.setValue(0);
        sl125.setRequestFocusEnabled(false);
        sl125.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl125MouseDragged(evt);
            }
        });

        sl250.setMaximum(8);
        sl250.setMinimum(-8);
        sl250.setMinorTickSpacing(2);
        sl250.setOrientation(javax.swing.JSlider.VERTICAL);
        sl250.setPaintTicks(true);
        sl250.setValue(0);
        sl250.setRequestFocusEnabled(false);
        sl250.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl250MouseDragged(evt);
            }
        });

        sl500.setMaximum(8);
        sl500.setMinimum(-8);
        sl500.setMinorTickSpacing(2);
        sl500.setOrientation(javax.swing.JSlider.VERTICAL);
        sl500.setPaintTicks(true);
        sl500.setValue(0);
        sl500.setRequestFocusEnabled(false);
        sl500.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl500MouseDragged(evt);
            }
        });

        sl1K.setMaximum(8);
        sl1K.setMinimum(-8);
        sl1K.setMinorTickSpacing(2);
        sl1K.setOrientation(javax.swing.JSlider.VERTICAL);
        sl1K.setPaintTicks(true);
        sl1K.setValue(0);
        sl1K.setRequestFocusEnabled(false);
        sl1K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl1KMouseDragged(evt);
            }
        });

        sl2K.setMaximum(8);
        sl2K.setMinimum(-8);
        sl2K.setMinorTickSpacing(2);
        sl2K.setOrientation(javax.swing.JSlider.VERTICAL);
        sl2K.setPaintTicks(true);
        sl2K.setValue(0);
        sl2K.setRequestFocusEnabled(false);
        sl2K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl2KMouseDragged(evt);
            }
        });

        sl16K.setMaximum(8);
        sl16K.setMinimum(-8);
        sl16K.setMinorTickSpacing(2);
        sl16K.setOrientation(javax.swing.JSlider.VERTICAL);
        sl16K.setPaintTicks(true);
        sl16K.setValue(0);
        sl16K.setRequestFocusEnabled(false);
        sl16K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl16KMouseDragged(evt);
            }
        });

        sl8K.setMaximum(8);
        sl8K.setMinimum(-8);
        sl8K.setMinorTickSpacing(2);
        sl8K.setOrientation(javax.swing.JSlider.VERTICAL);
        sl8K.setPaintTicks(true);
        sl8K.setValue(0);
        sl8K.setRequestFocusEnabled(false);
        sl8K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl8KMouseDragged(evt);
            }
        });

        sl4K.setMaximum(8);
        sl4K.setMinimum(-8);
        sl4K.setMinorTickSpacing(2);
        sl4K.setOrientation(javax.swing.JSlider.VERTICAL);
        sl4K.setPaintTicks(true);
        sl4K.setValue(0);
        sl4K.setRequestFocusEnabled(false);
        sl4K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sl4KMouseDragged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel13.setText("+12 dB");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel14.setText("-12 dB");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel15.setText("0 dB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbActivoEcualizador)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slPreamplificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEcualizador, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sl32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sl64, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl125, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(sl250, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(sl500, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sl1K, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sl2K, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sl4K, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sl8K, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sl16K, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEcualizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbActivoEcualizador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slPreamplificador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sl32, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl64, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl125, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl250, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl500, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl1K, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl2K, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl4K, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl8K, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(sl16K, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void ModificaSliders(int val32, int val64, int val125, int val250, int val500, int val1K, int val2K, int val4K, int val8K, int val16K){
        sl32.setValue(val32); sl64.setValue(val64); sl125.setValue(val125); sl250.setValue(val250); sl500.setValue(val500);
        sl1K.setValue(val1K); sl2K.setValue(val2K); sl4K.setValue(val4K); sl8K.setValue(val8K); sl16K.setValue(val16K);
    }
    
    private void cbEcualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEcualizadorActionPerformed
        String modo = cbEcualizador.getSelectedItem().toString();
        switch(modo){
            case "Uniforme":
                ModificaSliders(0, 0, 0, 0, 0, 0, 0, 0, 0,0);
                VP.CambiaIcono(VP.lModoEcuVP, "uniforme azul.png","iconos");
                break; 
            case "Pop":
                ModificaSliders(-1,-1,0,1,2,2,1,0,-1,-1);
                VP.CambiaIcono(VP.lModoEcuVP, "pop azul.png","iconos");
                break;
            case "Rock":
                ModificaSliders(3,2,2,1,0,-1,0,1,2,3);
                VP.CambiaIcono(VP.lModoEcuVP, "rock azul.png","iconos");
                break;
            case "Amplificador de bajos":
                ModificaSliders(0,0,0,0,0,1,2,3,4,5);
                VP.CambiaIcono(VP.lModoEcuVP, "bajos azul.png","iconos");
                break;
            case "Amplificador de agudos":
                ModificaSliders(5,4,3,2,1,0,0,0,0,0);
                VP.CambiaIcono(VP.lModoEcuVP, "agudos azul.png","iconos");
                break;  
            case "Manual":
                VP.CambiaIcono(VP.lModoEcuVP, "manual azul.png","iconos");
                break;
        }
                
    }//GEN-LAST:event_cbEcualizadorActionPerformed

    private void cbActivoEcualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActivoEcualizadorActionPerformed
        if(cbActivoEcualizador.isSelected())
            VP.CambiaIcono(VP.lActivadoDesactivadoEcualizador, "tick azul.png","iconos");
        else
            VP.CambiaIcono(VP.lActivadoDesactivadoEcualizador, "cruz gris.png","iconos");
    }//GEN-LAST:event_cbActivoEcualizadorActionPerformed

    private void slPreamplificadorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slPreamplificadorMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_slPreamplificadorMouseDragged

    private void sl32MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl32MouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl32MouseDragged

    private void sl64MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl64MouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl64MouseDragged

    private void sl125MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl125MouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl125MouseDragged

    private void sl250MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl250MouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl250MouseDragged

    private void sl500MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl500MouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl500MouseDragged

    private void sl1KMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl1KMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl1KMouseDragged

    private void sl2KMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl2KMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl2KMouseDragged

    private void sl4KMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl4KMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl4KMouseDragged

    private void sl8KMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl8KMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl8KMouseDragged

    private void sl16KMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl16KMouseDragged
        //Si modificamos a mano el valor de un slider tenemos que pasar a modo manual
        ModoManual();
    }//GEN-LAST:event_sl16KMouseDragged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    
    public void ModoManual(){
        //Modificamos el combo box de Ecualizador
        cbEcualizador.setSelectedItem("Manual");
        //Modificamos el icono de la VP
        VP.CambiaIcono(VP.lModoEcuVP, "manual azul.png","iconos");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ecualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ecualizador().setVisible(true);
            }
        });
    }
    
    //Referencia a la ventana principal
    VentanaPrincipal VP;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbActivoEcualizador;
    private javax.swing.JComboBox<String> cbEcualizador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider sl125;
    private javax.swing.JSlider sl16K;
    private javax.swing.JSlider sl1K;
    private javax.swing.JSlider sl250;
    private javax.swing.JSlider sl2K;
    private javax.swing.JSlider sl32;
    private javax.swing.JSlider sl4K;
    private javax.swing.JSlider sl500;
    private javax.swing.JSlider sl64;
    private javax.swing.JSlider sl8K;
    private javax.swing.JSlider slPreamplificador;
    // End of variables declaration//GEN-END:variables
}
